name: Run App tests

on:
  push:
    branches: [ master, development]
  pull_request:
    branches: [ master ]

jobs:
  test-and-analyze-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
        working-directory: ./courier_driver_tracker
      - run: flutter test
        working-directory: ./courier_driver_tracker
      - run: flutter analyze
        working-directory: ./courier_driver_tracker
