name: Run Demo1 tests

on:
  push:
    branches: [ master, development, test/demo1-unit-test]
  pull_request:
    branches: [ master ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
        working-directory: ./courier_driver_tracker
      - run: flutter build aot
        working-directory: ./courier_driver_tracker
      - run: flutter test
        working-directory: ./courier_driver_tracker
      - run: flutter analyze
        working-directory: ./courier_driver_tracker
